site_name: Hass Agent Documentation
site_url: https://hass-agent.github.io/
site_author: DrR0X
site_description: >-
  Access your homeassistant from any windows machine - send notifications, collect data and automate repetitive tasks

repo_url: https://github.com/hass-agent/hass-agent.github.io
repo_name: HASS.Agent Docs Repo

copyright: >
  Copyright &copy; 2023 <a href="https://github.com/DrR0X-glitch" target="_blank" rel="noopener">DrR0x</a> -
  <a href="#__consent">Change cookie settings</a>

theme:
  name: material
  custom_dir: theme_override_home
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - toc.integrate # TOC is table of contents
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: custom
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: custom
      accent: purple
  favicon: assets/images/logo/logo-128-round.png
  logo: assets/images/logo/logo-128.png

plugins:
  - mike:
      canonical_version: latest
  # - social:
  #     enabled: !ENV [CI, false]
  #     cards_layout: default/variant
  #     cards_layout_options:
  #       background_image: layouts/HASS.Agent-Social-Card.png
  #       background_color: transparent
  #       color: #ffffff
  - search

# Add stylesheet for custom color scheme
extra_css:
  - stylesheets/extra.css

# Add social icons to footer
extra:
  version:
    provider: mike
  analytics:
    provider: google
    property: G-TBLK7V0HW7
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback!
  consent:
    actions:
      - accept
      - reject
      - manage
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/LAB02-Research/HASS.Agent
    - icon: fontawesome/solid/mug-hot
      link: https://ko-fi.com/lab02research

markdown_extensions:
  - tables
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg # Page Tree


nav:
  - Home: index.md
  - Getting Started:
      - Start Here: getting-started/index.md
      - Installation: getting-started/installation.md
  - Helping Out:
      - Start Here: contributing/index.md
      - Reporting Issues: contributing/reporting-issues.md
      - Developing the App:
          - Start Here: contributing/hass-agent-app/index.md
      - Developing the Integration:
          - Start Here: contributing/hass-agent-integration/index.md
      - Developing the Documentation:
          - Start Here: contributing/hass-agent-documentation/index.md
          - Setup: contributing/hass-agent-documentation/setup.md
          - Development Lifecycle: contributing/hass-agent-documentation/development-lifecycle.md
      - Extra Resources:
          - Info: contributing/developer-resources/index.md
          - Version System: contributing/developer-resources/version-system.md
